backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artPosts"
    label: "Art Posts"
    folder: "./src/art"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "art-post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Notes", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYY-MM-DD", format: "L" }
      - { label: "Software", name: "software", widget: "markdown" }

  - name: "blogPosts"
    label: "Blog Posts"
    folder: "./src/writing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog-post.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Post Body", name: "body", widget: "markdown" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "YYY-MM-DD", format: "L" }
